set(CMAKE_SYSTEM_NAME Windows)
string(REGEX REPLACE "[/\\]$" "" CMAKE_SYSTEM_VERSION "$ENV{WindowsSDKVersion}")

set(WIN_TARGET_ARCH $ENV{VSCMD_ARG_TGT_ARCH})

file(TO_CMAKE_PATH "$ENV{VCToolsInstallDir}" MSVC_TOOLS)
string(REGEX REPLACE "[/\\]$" "" MSVC_TOOLS "${MSVC_TOOLS}")
set(MSVC_TOOLS "${MSVC_TOOLS}/bin/Hostx64/${WIN_TARGET_ARCH}")

set(MSVC_COMPILER "${MSVC_TOOLS}/cl.exe")

set(CMAKE_C_COMPILER ${MSVC_COMPILER})
set(CMAKE_CXX_COMPILER ${MSVC_COMPILER})

message(STATUS "[Toolchain] CMAKE_SYSTEM_NAME    : ${CMAKE_SYSTEM_NAME}")
message(STATUS "[Toolchain] CMAKE_SYSTEM_VERSION : ${CMAKE_SYSTEM_VERSION}")
message(STATUS "[Toolchain] CMAKE_BUILD_TYPE     : ${CMAKE_BUILD_TYPE}")
message(STATUS "[Toolchain] WIN_TARGET_ARCH      : ${WIN_TARGET_ARCH}")
message(STATUS "[Toolchain] CMAKE_C_COMPILER     : ${CMAKE_C_COMPILER}")
message(STATUS "[Toolchain] CMAKE_CXX_COMPILER   : ${CMAKE_CXX_COMPILER}")
