parameters:
  - name: DependsOn
    type: string
    default: ''

jobs:
- job: LinuxBuild
  displayName: Build
  ${{ if ne(parameters.DependsOn, '') }}:
    dependsOn: ${{ parameters.DependsOn }}
  ${{ if ne(parameters.DependsOn, '') }}:
    condition: succeeded()
  timeoutInMinutes: 30
  cancelTimeoutInMinutes: 2
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix:
      Linux_Debug:
        MsoPlatform: LINUX
        BuildConfiguration: Debug
      Linux_Release:
        MsoPlatform: LINUX
        BuildConfiguration: Release
  steps:
    - template: posix-build-steps.yml
