parameters:
  - name: DependsOn
    type: string
    default: ''

jobs:
- job: WindowsBuild
  displayName: Build
  ${{ if ne(parameters.DependsOn, '') }}:
    dependsOn: ${{ parameters.DependsOn }}
  ${{ if ne(parameters.DependsOn, '') }}:
    condition: succeeded()
  timeoutInMinutes: 30
  cancelTimeoutInMinutes: 2
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      Win32_X86_Debug:
        MsoPlatform: WIN32
        BuildConfiguration: Debug
        BuildPlatform: x86
      Win32_X86_Release:
        MsoPlatform: WIN32
        BuildConfiguration: Release
        BuildPlatform: x86
      Win32_X64_Debug:
        MsoPlatform: WIN32
        BuildConfiguration: Debug
        BuildPlatform: x64
      Win32_X64_Release:
        MsoPlatform: WIN32
        BuildConfiguration: Release
        BuildPlatform: x64
      WinRT_X86_Debug:
        MsoPlatform: WINRT
        BuildConfiguration: Debug
        BuildPlatform: x86
      WinRT_X86_Release:
        MsoPlatform: WINRT
        BuildConfiguration: Release
        BuildPlatform: x86
      WinRT_X64_Debug:
        MsoPlatform: WINRT
        BuildConfiguration: Debug
        BuildPlatform: x64
      WinRT_X64_Release:
        MsoPlatform: WINRT
        BuildConfiguration: Release
        BuildPlatform: x64
  steps:
    - checkout: self
      clean: false
      submodules: false

    - script: choco install ninja
      displayName: Install Ninja

    - task: BatchScript@1
      displayName: Setup Visual C++ Environment
      inputs:
        filename: .ado\vcenv.bat
        modifyEnvironment: true

    - task: CMake@1
      displayName: Generate Ninja scripts
      inputs:
        workingDirectory: $(Build.BinariesDirectory)/$(MsoPlatform)/$(BuildConfiguration)/$(BuildPlatform)
        cmakeArgs: -G Ninja -DMSO_LIBLET_PLATFORM=$(MsoPlatform) -DCMAKE_BUILD_TYPE=$(BuildConfiguration) -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_VERSION=$(BuildWindowsSDK) $(Build.SourcesDirectory)

    - task: CMake@1
      displayName: Build
      inputs:
        workingDirectory: $(Build.BinariesDirectory)/$(MsoPlatform)/$(BuildConfiguration)/$(BuildPlatform)
        cmakeArgs: --build .

    - task: CMake@1
      displayName: Stage built files
      inputs:
        workingDirectory: $(Pipeline.Workspace)
        cmakeArgs: --install $(Build.BinariesDirectory)/$(MsoPlatform)/$(BuildConfiguration)/$(BuildPlatform) --prefix tests --component tests

    - script: activeObject_tests
      displayName: Liblet tests - activeObject
      workingDirectory: $(Pipeline.Workspace)/tests/$(MsoPlatform)/$(BuildConfiguration)/$(BuildPlatform)

    - script: errorCode_tests
      displayName: Liblet tests - activeObject
      workingDirectory: $(Pipeline.Workspace)/tests/$(MsoPlatform)/$(BuildConfiguration)/$(BuildPlatform)

    - script: eventWaitHandle_tests
      displayName: Liblet tests - eventWaitHandle
      workingDirectory: $(Pipeline.Workspace)/tests/$(MsoPlatform)/$(BuildConfiguration)/$(BuildPlatform)

    - script: functional_tests
      displayName: Liblet tests - functional
      workingDirectory: $(Pipeline.Workspace)/tests/$(MsoPlatform)/$(BuildConfiguration)/$(BuildPlatform)

    - script: future_tests
      displayName: Liblet tests - future
      workingDirectory: $(Pipeline.Workspace)/tests/$(MsoPlatform)/$(BuildConfiguration)/$(BuildPlatform)

    - script: guid_tests
      displayName: Liblet tests - guid
      workingDirectory: $(Pipeline.Workspace)/tests/$(MsoPlatform)/$(BuildConfiguration)/$(BuildPlatform)

    - script: object_tests
      displayName: Liblet tests - object
      workingDirectory: $(Pipeline.Workspace)/tests/$(MsoPlatform)/$(BuildConfiguration)/$(BuildPlatform)

    - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
      displayName: 📒 Generate Manifest Windows
      inputs:
        BuildDropPath: $(Build.BinariesDirectory)/$(MsoPlatform)/$(BuildConfiguration)/$(BuildPlatform)

    - task: PublishPipelineArtifact@1
      displayName: 📒 Publish Manifest  Windows
      inputs:
        artifactName: SBom- Windows-$(BuildConfiguration)-$(System.JobAttempt)
        targetPath: $(Build.BinariesDirectory)/$(MsoPlatform)/$(BuildConfiguration)/$(BuildPlatform)/_manifest